fix fcm kernel req
ERROR: files are incompatible: Runtime info and framework compatibility
matrix are incompatible: No compatible kernel requirement found (kernel
FCM version = 6).
For kernel requirements at matrix level 6, Kernel config errors:
    Missing config CONFIG_SONY_FF
    Missing config CONFIG_TRACE_GPU_MEM