add missing dependencies, fix soname for fp
FIX: FP BLOB SONAME

[ 99% 4175/4217 3m27s remaining] Check prebuilt ELF binary:
out/soong/.intermediates/vendor/infinix/X670/prebuilt_fingerprint.default/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/fingerprint.default.so
FAILED:
out/target/product/X670/obj/SHARED_LIBRARIES/fingerprint.default_intermediates/check_elf_files.timestamp
/bin/bash -c "(rm -f
out/target/product/X670/obj/SHARED_LIBRARIES/fingerprint.default_intermediates/check_elf_files.timestamp
) && (out/host/linux-x86/bin/check_elf_file
--skip-bad-elf-magic 	    --skip-unknown-elf-machine

--soname fingerprint.default.so 	    --shared-lib
out/target/product/X670/obj/SHARED_LIBRARIES/libMcClient_intermediates/libMcClient.so
--shared-lib
out/target/product/X670/obj/SHARED_LIBRARIES/liblog.vendor_intermediates/liblog.vendor.so
--shared-lib
out/target/product/X670/obj/SHARED_LIBRARIES/libc.vendor_intermediates/libc.vendor.so
--shared-lib
out/target/product/X670/obj/SHARED_LIBRARIES/libm.vendor_intermediates/libm.vendor.so
--shared-lib out/target/product/X670/obj/SHARED_
LIBRARIES/libc++.vendor_intermediates/libc++.vendor.so --shared-lib
out/target/product/X670/obj/SHARED_LIBRARIES/libdl.vendor_intermediates/libdl.vendor.so
 	    --system-shared-lib libc --system-shared-lib libm
--system-shared-lib libdl

--llvm-readobj=prebuilts/clang/host/linux-x86/clang-r536225/bin/llvm-readobj

out/soong/.intermediates/vendor/infinix/X670/prebuilt_fingerprint.default/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/fingerprint.defa
ult.so ) && (touch
out/target/product/X670/obj/SHARED_LIBRARIES/fingerprint.default_intermediates/check_elf_files.timestamp
)"
out/soong/.intermediates/vendor/infinix/X670/prebuilt_fingerprint.default/android_vendor_arm64_armv8-2a-dotprod_cortex-a76_shared/fingerprint.default.so:
error: DT_SONAME "fingerprint" must be equal to the file name
"fingerprint.default.so".
23:31:20 ninja failed with: exit status 1