props: Disable bluetooth powerstats
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector: Cannot
acquire BluetoothActivityEnergyInfo
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
java.util.concurrent.ExecutionException: java.lang.RuntimeException:
error: 9
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:372)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2072)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.power.stats.BluetoothPowerStatsCollector.collectBluetoothActivityInfo(BluetoothPowerStatsCollector.java:181)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.power.stats.BluetoothPowerStatsCollector.collectStats(BluetoothPowerStatsCollector.java:149)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.power.stats.PowerStatsCollector.collectAndDeliverStats(PowerStatsCollector.java:176)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.power.stats.PowerStatsCollector$$ExternalSyntheticLambda0.run(R8$$SyntheticClass:0)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at android.os.Handler.handleCallback(Handler.java:991)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at android.os.Handler.dispatchMessage(Handler.java:102)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at android.os.Looper.loopOnce(Looper.java:232)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at android.os.Looper.loop(Looper.java:317)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at android.os.HandlerThread.run(HandlerThread.java:85)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector: Caused
by: java.lang.RuntimeException: error: 9
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.power.stats.BluetoothPowerStatsCollector$1.onBluetoothActivityEnergyInfoError(BluetoothPowerStatsCollector.java:170)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
android.bluetooth.BluetoothAdapter$OnBluetoothActivityEnergyInfoProxy.lambda$onError$2(BluetoothAdapter.java:1063)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
android.bluetooth.BluetoothAdapter$OnBluetoothActivityEnergyInfoProxy$$ExternalSyntheticLambda0.run(D8$$SyntheticClass:0)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
android.bluetooth.BluetoothUtils.lambda$executeFromBinder$0(BluetoothUtils.java:343)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
android.bluetooth.BluetoothUtils$$ExternalSyntheticLambda1.run(D8$$SyntheticClass:0)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.SystemServerInitThreadPool$$ExternalSyntheticLambda0.execute(R8$$SyntheticClass:0)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
android.bluetooth.BluetoothUtils.executeFromBinder(BluetoothUtils.java:343)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
android.bluetooth.BluetoothAdapter$OnBluetoothActivityEnergyInfoProxy.onError(BluetoothAdapter.java:1062)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
android.bluetooth.BluetoothAdapter.requestControllerActivityEnergyInfo(BluetoothAdapter.java:2769)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.power.stats.BatteryStatsImpl$BluetoothStatsRetrieverImpl.requestControllerActivityEnergyInfo(BatteryStatsImpl.java:401)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
at
com.android.server.power.stats.BluetoothPowerStatsCollector.collectBluetoothActivityInfo(BluetoothPowerStatsCollector.java:159)
04-23 12:42:42.537  1787  1833 E BluetoothPowerStatsCollector:
... 8 more